config/routes.rb
Rails.application.routes.draw do
  # 追記する
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only:  [:show, :edit, :update, :destroy] 
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render :new
    end
  end
  # 定義する
  def show
    @blog = Blog.find(params[:id])   # 重複！
  end
  def edit
    @blog = Blog.find(params[:id])   # 重複！
  end
  def update
    @blog = Blog.find(params[:id])   # 重複！
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  private
  def blog_params
    params.require(:blog).permit(:Name, :Email, :content)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="blog_Name">
        <%= form.label :Name %>
        <%= form.text_field :Name %>
    </div>
        <div class="blog_Email">
        <%= form.label :Email %>
        <%= form.text_field :Email %>
    </div>
    <div class="blog_content">
        <%= form.label :content %>
        <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>
  <%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Content</th>
    </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.Name %></td>
    <td><%= blog.Email %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <%= link_to "ブログを編集する", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %>
    <%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
    </tr>
<% end %>
</table>
<br>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<%= form_with(model: Blog.new, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_Name">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>
  <div class="blog_Email">
  <%= form.label :Email %>
  <%= form.text_field :Email %>
</div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>Email: <%= @blog.Email %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>